version: '3'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    container_name: postgresql
    restart: always
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=kong
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=kong
    networks:
      - rentail-application
  
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: bd-cars
      MYSQL_USER: db_application
      MYSQL_PASSWORD: superSecret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rentail-application
 
      
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_USERNAME: db_application
      MONGO_INITDB_PASSWORD: superSecret
      MONGO_INITDB_DATABASE: bd-rental
    networks:
      - rentail-application
     
  reservation:
    restart: always
    container_name: reservation
    image: nicolasdockerbdb/facade-reservation-mngr:0.0.6-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://db_application:superSecret@mongodb:27017/bd-rental
    networks:
      - rentail-application
    depends_on:
      - kong
      - mongodb
      
  kong:
    image: docker.io/bitnami/kong:2.6.0
    container_name: kong
    restart: always
    ports:
      - 8000:8000
      - 8443:8443
    environment:
      - KONG_MIGRATE=yes
      - KONG_PG_HOST=postgresql
      - KONG_PG_PASSWORD=bitnami
    networks:
      - rentail-application
    depends_on:
      - postgresql
      
volumes:
  postgresql_data:
    driver: local
  mysql_data:
    driver: local
    
networks:
    rentail-application:
        driver: bridge
        
        